/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlBibliotecario;
import Controlador.CtlLector;
import Controlador.CtlAdministrador;
import Modelo.Lector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian Cruz
 */
public class FrmGestionLector extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionLector
     */
    private CtlLector controlador;
    private CtlBibliotecario controlador2;
    private CtlAdministrador controlador3;
    
    public FrmGestionLector() {
        initComponents();
        this.setLocationRelativeTo(this);
        setResizable(false);
        btnModificarLector.setEnabled(false);
        btnCancelarLector.setVisible(false);
        controlador = new CtlLector();
        controlador2 = new CtlBibliotecario();
        controlador3 = new CtlAdministrador();
         listarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarLector = new javax.swing.JButton();
        btnCancelarLector = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLectorBiblioteca = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtNombreLector = new javax.swing.JTextField();
        txtCodigoLector = new javax.swing.JTextField();
        txtCedulaLector = new javax.swing.JTextField();
        txtDireccionLector = new javax.swing.JTextField();
        txtCorreoLector = new javax.swing.JTextField();
        btnRegistrarLector = new javax.swing.JButton();
        btnModificarLector = new javax.swing.JButton();
        btnEliminarLector = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnBuscarLector.setText("Buscar");
        btnBuscarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLectorActionPerformed(evt);
            }
        });

        btnCancelarLector.setText("Cancelar");
        btnCancelarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLectorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setText("Gestion Lectores");

        jLabel2.setText("Nombre Completo :");

        jLabel3.setText("Codigo :");

        jLabel4.setText("Cedula :");

        jLabel5.setText("Direccion :");

        tblLectorBiblioteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Cedula", "Direccion", "Correo"
            }
        ));
        jScrollPane2.setViewportView(tblLectorBiblioteca);

        jLabel6.setText("Correo :");

        txtNombreLector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreLectorKeyTyped(evt);
            }
        });

        txtCodigoLector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoLectorKeyTyped(evt);
            }
        });

        txtCedulaLector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaLectorKeyTyped(evt);
            }
        });

        btnRegistrarLector.setText("Registrar");
        btnRegistrarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLectorActionPerformed(evt);
            }
        });

        btnModificarLector.setText("Modificar");
        btnModificarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLectorActionPerformed(evt);
            }
        });

        btnEliminarLector.setText("Eliminar");
        btnEliminarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombreLector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtCodigoLector, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaLector, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionLector, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreoLector, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnRegistrarLector)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarLector)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarLector, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnBuscarLector, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancelarLector)
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCodigoLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtCedulaLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtDireccionLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCorreoLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarLector)
                    .addComponent(btnModificarLector)
                    .addComponent(btnEliminarLector)
                    .addComponent(btnBuscarLector)
                    .addComponent(btnCancelarLector))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLectorActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
        txtCedulaLector.setEditable(true);
        btnModificarLector.setEnabled(false);
        btnCancelarLector.setVisible(false);
        btnRegistrarLector.setEnabled(true);
        
    }//GEN-LAST:event_btnCancelarLectorActionPerformed

    private void btnRegistrarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLectorActionPerformed
        // TODO add your handling code here:
        
        if (txtNombreLector.getText().isEmpty()
                    || txtCodigoLector.getText().isEmpty()
                    || txtCedulaLector.getText().isEmpty()
                    || txtDireccionLector.getText().isEmpty()
                    || txtCorreoLector.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");

            } else {

                String nombreUsuario,
                        codigoUsuario,
                        cedulaUsuario,
                        direccionUsuario,
                        correoUsuario;

                nombreUsuario = txtNombreLector.getText();
                codigoUsuario = txtCodigoLector.getText();
                cedulaUsuario = txtCedulaLector.getText();
                direccionUsuario = txtDireccionLector.getText();
                correoUsuario = txtCorreoLector.getText();

                Lector lector = new Lector(codigoUsuario, cedulaUsuario, nombreUsuario, direccionUsuario, correoUsuario);

                if (controlador.verificarLector(lector.getCodigo(), lector.getCedula())
                        && controlador2.verificarBibliotecario(lector.getCodigo(), lector.getCedula())
                        && controlador3.verificarAdministrador(lector.getCodigo(), lector.getCedula())) {

                    controlador.registrarLector(lector);
                    JOptionPane.showMessageDialog(null, "El lector se ha registrado ");
                    LimpiarCampos();
                    listarTablas();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar el lector");
                }

            }
        
    }//GEN-LAST:event_btnRegistrarLectorActionPerformed

    private void btnModificarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLectorActionPerformed
        // TODO add your handling code here:
        
           if (txtNombreLector.getText().isEmpty()
                    || txtCodigoLector.getText().isEmpty()
                    || txtCedulaLector.getText().isEmpty()
                    || txtDireccionLector.getText().isEmpty()
                    || txtCorreoLector.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");

            } else {

                String nombreUsuario,
                        codigoUsuario,
                        cedulaUsuario,
                        direccionUsuario,
                        correoUsuario;

                nombreUsuario = txtNombreLector.getText();
                codigoUsuario = txtCodigoLector.getText();
                cedulaUsuario = txtCedulaLector.getText();
                direccionUsuario = txtDireccionLector.getText();
                correoUsuario = txtCorreoLector.getText();

                controlador.editarLector(codigoUsuario, cedulaUsuario, nombreUsuario, direccionUsuario, correoUsuario);
                JOptionPane.showMessageDialog(null, "El usuario se ha modificado ");
                LimpiarCampos();
                listarTablas();
               
                txtCedulaLector.setEditable(true);
                btnModificarLector.setEnabled(false);
                btnCancelarLector.setVisible(false);
                btnRegistrarLector.setEnabled(true);
            }
    
        
    }//GEN-LAST:event_btnModificarLectorActionPerformed

    private void btnEliminarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLectorActionPerformed
        // TODO add your handling code here:
        
         String cedula = JOptionPane.showInputDialog("Introduzca la cedula del usuario a eliminar");
         
         if (controlador.eliminarLector(cedula)) {
            JOptionPane.showMessageDialog(null, "Eliminado Correctamente el lector",
                    "Informe", JOptionPane.INFORMATION_MESSAGE);
         } else {
            JOptionPane.showMessageDialog(null, "No se ha podido eliminar");
        }

        listarTablas();
        
    }//GEN-LAST:event_btnEliminarLectorActionPerformed

    private void btnBuscarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLectorActionPerformed
        // TODO add your handling code here:
        
         String cedula = JOptionPane.showInputDialog("Ingrese la cedula del Usuario");
         
          Lector lector = controlador.buscarLector(cedula);
         
          if (lector != null) {
            txtNombreLector.setText(lector.getNombreCompleto());
            txtCedulaLector.setText(lector.getCedula());
            txtCedulaLector.setEditable(false);
            txtCodigoLector.setText(lector.getCodigo());
            txtCorreoLector.setText(lector.getCorreo());
            txtDireccionLector.setText(lector.getDireccion());
            btnModificarLector.setEnabled(true);
            btnCancelarLector.setVisible(true);
            btnRegistrarLector.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido encontrar el usuario");
        }
          
          
    }//GEN-LAST:event_btnBuscarLectorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
         controlador.guardarArchivoL();
    }//GEN-LAST:event_formWindowClosed

    private void txtNombreLectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreLectorKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreLectorKeyTyped

    private void txtCodigoLectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoLectorKeyTyped
        // TODO add your handling code here
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtCodigoLectorKeyTyped

    private void txtCedulaLectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaLectorKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaLectorKeyTyped

     public void LimpiarCampos() {

        txtNombreLector.setText("");
        txtCodigoLector.setText("");
        txtCorreoLector.setText("");
        txtCedulaLector.setText("");
        txtDireccionLector.setText("");
    }
    
        public void listarTablas() {

        DefaultTableModel modelo3;
        modelo3 = controlador.listarL();
        tblLectorBiblioteca.setModel(modelo3);
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionLector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionLector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionLector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionLector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionLector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarLector;
    private javax.swing.JButton btnCancelarLector;
    private javax.swing.JButton btnEliminarLector;
    private javax.swing.JButton btnModificarLector;
    private javax.swing.JButton btnRegistrarLector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLectorBiblioteca;
    private javax.swing.JTextField txtCedulaLector;
    private javax.swing.JTextField txtCodigoLector;
    private javax.swing.JTextField txtCorreoLector;
    private javax.swing.JTextField txtDireccionLector;
    private javax.swing.JTextField txtNombreLector;
    // End of variables declaration//GEN-END:variables
}
