/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlLibro;
import Controlador.CtlRevista;
import Modelo.Libro;
import Modelo.Revista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian Cruz
 */
public class FrmGestionMaterialBibliografico extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionMaterialBibliografico
     */
    private CtlLibro controladorl;
    private CtlRevista controladorr;

    public FrmGestionMaterialBibliografico() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        BloqueoPosicion0();
        btnModificarMaterial.setEnabled(false);
        btnCancelarMaterial.setVisible(false);
        controladorl = new CtlLibro();
        controladorr = new CtlRevista();
        listarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void BloqueoPosicion0() {

        if (cbTipoMaterial.getSelectedIndex() == 0) {
            txtNumeroMaterial.setVisible(true);
            txtVolumenMaterial.setVisible(true);
            cbDiasPrestamo.setVisible(true);
            txtEdicionMaterial.setVisible(true);
            txtNoPaginas.setVisible(true);
            txtAutores.setVisible(true);
            txtAsignaturaMaterial.setEnabled(false);
            txtAutores.setEnabled(false);
            txtAñoMaterial.setEnabled(false);
            txtEdicionMaterial.setEnabled(false);
            txtEditorialMaterial.setEnabled(false);
            txtIsbnOIssnMaterial.setEnabled(false);
            txtNoCopiasMaterial.setEnabled(false);
            txtNoPaginas.setEnabled(false);
            txtNumeroMaterial.setEnabled(false);
            txtTituloMaterial.setEnabled(false);
            txtVolumenMaterial.setEnabled(false);
            cbDiasPrestamo.setEnabled(false);
            jLabel5.setVisible(true);
            jLabel3.setVisible(true);
            jLabel9.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);

        }
    }

    public void limpiarCampos() {
        txtAsignaturaMaterial.setText("");
        txtAutores.setText("");
        txtAñoMaterial.setText("");
        txtEdicionMaterial.setText("");
        txtEditorialMaterial.setText("");
        txtIsbnOIssnMaterial.setText("");
        txtNoCopiasMaterial.setText("");
        txtNoPaginas.setText("");
        txtNumeroMaterial.setText("");
        txtTituloMaterial.setText("");
        txtVolumenMaterial.setText("");
        cbDiasPrestamo.setSelectedIndex(0);
        cbTipoMaterial.setSelectedIndex(0);

    }

    public void listarTablas() {

        DefaultTableModel modelo;
        modelo = controladorl.listarLb();
        tblLibro.setModel(modelo);

        DefaultTableModel modelo2;
        modelo2 = controladorr.listarRv();
        tblRevista.setModel(modelo2);

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnCancelarMaterial = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbDiasPrestamo = new javax.swing.JComboBox<>();
        txtNoCopiasMaterial = new javax.swing.JTextField();
        txtNoPaginas = new javax.swing.JTextField();
        txtEditorialMaterial = new javax.swing.JTextField();
        txtTituloMaterial = new javax.swing.JTextField();
        txtAñoMaterial = new javax.swing.JTextField();
        txtEdicionMaterial = new javax.swing.JTextField();
        txtAsignaturaMaterial = new javax.swing.JTextField();
        txtAutores = new javax.swing.JTextField();
        txtIsbnOIssnMaterial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarMaterial = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnModificarMaterial = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarMaterial = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarMaterial = new javax.swing.JButton();
        txtNumeroMaterial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtVolumenMaterial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRevista = new javax.swing.JTable();
        cbTipoMaterial = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel6.setText("Año :");

        btnCancelarMaterial.setText("Cancelar");
        btnCancelarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMaterialActionPerformed(evt);
            }
        });

        jLabel7.setText("Titulo :");

        jLabel8.setText("Editorial :");

        jLabel9.setText("No° Paginas :");

        jLabel10.setText("No° Copias :");

        jLabel11.setText("Dias de Prestamo:");

        cbDiasPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione una Opcion...", "2", "5" }));

        txtNoCopiasMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoCopiasMaterialKeyTyped(evt);
            }
        });

        txtNoPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoPaginasKeyTyped(evt);
            }
        });

        txtAñoMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoMaterialKeyTyped(evt);
            }
        });

        txtIsbnOIssnMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnOIssnMaterialKeyTyped(evt);
            }
        });

        tblLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Titulo", "Asignatura", "Año", "No° Copias", "No° Paginas"
            }
        ));
        jScrollPane1.setViewportView(tblLibro);

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setText("Gestion Material Bibliografico");

        jLabel2.setText("ISBN O ISSN:");

        btnRegistrarMaterial.setText("Registrar");
        btnRegistrarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMaterialActionPerformed(evt);
            }
        });

        jLabel3.setText("Autores :");

        btnModificarMaterial.setText("Modificar");
        btnModificarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMaterialActionPerformed(evt);
            }
        });

        jLabel4.setText("Asignatura :");

        btnEliminarMaterial.setText("Eliminar");
        btnEliminarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMaterialActionPerformed(evt);
            }
        });

        jLabel5.setText("Edicion :");

        btnBuscarMaterial.setText("Buscar");
        btnBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMaterialActionPerformed(evt);
            }
        });

        txtNumeroMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroMaterialKeyTyped(evt);
            }
        });

        jLabel12.setText("Numero :");

        jLabel13.setText("Volumen :");

        tblRevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISSN", "Titulo", "Asignatura", "Año", "No° Copias", "Volumen"
            }
        ));
        jScrollPane2.setViewportView(tblRevista);

        cbTipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opcion...", "Libro", "Revista" }));
        cbTipoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoMaterialActionPerformed(evt);
            }
        });

        jLabel14.setText("Tipo de Material :");

        jLabel15.setText("Libros");

        jLabel16.setText("Revistas");

        jLabel17.setText("jLabel17");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbTipoMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVolumenMaterial)
                    .addComponent(txtNumeroMaterial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbDiasPrestamo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNoCopiasMaterial)
                    .addComponent(txtNoPaginas)
                    .addComponent(txtEditorialMaterial)
                    .addComponent(txtTituloMaterial)
                    .addComponent(txtAñoMaterial)
                    .addComponent(txtEdicionMaterial)
                    .addComponent(txtAsignaturaMaterial)
                    .addComponent(txtAutores)
                    .addComponent(txtIsbnOIssnMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarMaterial)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarMaterial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarMaterial)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarMaterial))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(btnCancelarMaterial)))
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137)
                .addComponent(jLabel17)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIsbnOIssnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAsignaturaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEdicionMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAñoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTituloMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEditorialMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNoPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6))
                            .addComponent(txtNoCopiasMaterial))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbDiasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNumeroMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtVolumenMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarMaterial)
                            .addComponent(btnModificarMaterial)
                            .addComponent(btnEliminarMaterial)
                            .addComponent(btnBuscarMaterial))
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarMaterial)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMaterialActionPerformed
        // TODO add your handling code here:

        if (cbTipoMaterial.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(null, "Selecciona algun usuario y llena los campos");

        } else if (cbTipoMaterial.getSelectedIndex() == 1) {

            if (txtAsignaturaMaterial.getText().isEmpty()
                    || txtIsbnOIssnMaterial.getText().isEmpty()
                    || txtTituloMaterial.getText().isEmpty()
                    || txtAñoMaterial.getText().isEmpty()
                    || txtEditorialMaterial.getText().isEmpty()
                    || txtAutores.getText().isEmpty()
                    || txtNoCopiasMaterial.getText().isEmpty()
                    || txtNoPaginas.getText().isEmpty()
                    || cbDiasPrestamo.getSelectedIndex() == 0
                    || txtEdicionMaterial.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");

            } else {

                String asignaturaMaterial,
                        tituloMaterial,
                        editorialMaterial,
                        autoresLibro,
                        edicionlibro;

                int añoMaterial = 0, noCopiasMaterial = 0, noPaginasLibro = 0, isbnoissnMaterial = 0, diasPrestamoLibro = 0;

                asignaturaMaterial = txtAsignaturaMaterial.getText();
                isbnoissnMaterial = Integer.parseInt(txtIsbnOIssnMaterial.getText());
                tituloMaterial = txtTituloMaterial.getText();
                editorialMaterial = txtEditorialMaterial.getText();
                autoresLibro = txtAutores.getText();
                edicionlibro = txtEdicionMaterial.getText();
                añoMaterial = Integer.parseInt(txtAñoMaterial.getText());
                noCopiasMaterial = Integer.parseInt(txtNoCopiasMaterial.getText());
                noPaginasLibro = Integer.parseInt(txtNoPaginas.getText());

                switch (cbDiasPrestamo.getSelectedIndex()) {
                    case 1:
                        diasPrestamoLibro = 2;
                        break;
                    case 2:
                        diasPrestamoLibro = 5;
                        break;
                }

                Libro libro = new Libro(autoresLibro, edicionlibro, noPaginasLibro, diasPrestamoLibro, tituloMaterial, editorialMaterial, añoMaterial, asignaturaMaterial, noCopiasMaterial, isbnoissnMaterial);

                if (controladorl.verificarLibro(libro.getIsbnoIssn())
                        && controladorr.verificarRevista(libro.getIsbnoIssn())) {

                    if (controladorl.registrarLibro(libro)) {
                        JOptionPane.showMessageDialog(null, "El libro se ha registrado ");
                        limpiarCampos();
                        listarTablas();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al registrar el libro");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Ya hay un material bibliografico con ese código");

                }

            }

        } else {

            if (txtAsignaturaMaterial.getText().isEmpty()
                    || txtIsbnOIssnMaterial.getText().isEmpty()
                    || txtTituloMaterial.getText().isEmpty()
                    || txtAñoMaterial.getText().isEmpty()
                    || txtEditorialMaterial.getText().isEmpty()
                    || txtVolumenMaterial.getText().isEmpty()
                    || txtNoCopiasMaterial.getText().isEmpty()
                    || txtNumeroMaterial.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");

            } else {

                String asignaturaMaterial,
                        tituloMaterial,
                        editorialMaterial,
                        volumen;

                int añoMaterial = 0, noCopiasMaterial = 0, numero = 0, isbnoissnMaterial = 0;

                asignaturaMaterial = txtAsignaturaMaterial.getText();
                isbnoissnMaterial = Integer.parseInt(txtIsbnOIssnMaterial.getText());
                tituloMaterial = txtTituloMaterial.getText();
                editorialMaterial = txtEditorialMaterial.getText();
                volumen = txtVolumenMaterial.getText();
                añoMaterial = Integer.parseInt(txtAñoMaterial.getText());
                noCopiasMaterial = Integer.parseInt(txtNoCopiasMaterial.getText());
                numero = Integer.parseInt(txtNumeroMaterial.getText());

                Revista revista = new Revista(volumen, numero, tituloMaterial, editorialMaterial, añoMaterial, asignaturaMaterial, noCopiasMaterial, isbnoissnMaterial);

                if (controladorl.verificarLibro(revista.getIsbnoIssn())
                        && controladorr.verificarRevista(revista.getIsbnoIssn())) {

                    if (controladorr.registrarRevista(revista)) {
                        JOptionPane.showMessageDialog(null, "La revista se ha registrado ");
                        limpiarCampos();
                        listarTablas();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al registrar la revista");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Ya hay un material bibliografico con ese código");

                }
            }

        }


    }//GEN-LAST:event_btnRegistrarMaterialActionPerformed

    private void cbTipoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoMaterialActionPerformed
        // TODO add your handling code here:

        BloqueoPosicion0();

        if (cbTipoMaterial.getSelectedIndex() == 1) {
            txtAsignaturaMaterial.setEnabled(true);
            txtAñoMaterial.setEnabled(true);
            txtTituloMaterial.setEnabled(true);
            txtEditorialMaterial.setEnabled(true);
            txtNoCopiasMaterial.setEnabled(true);
            txtAutores.setEnabled(true);
            txtEdicionMaterial.setEnabled(true);
            txtNoPaginas.setEnabled(true);
            txtIsbnOIssnMaterial.setEnabled(true);
            cbDiasPrestamo.setEnabled(true);
            txtAutores.setVisible(true);
            txtEdicionMaterial.setVisible(true);
            txtNoPaginas.setVisible(true);
            cbDiasPrestamo.setVisible(true);
            jLabel5.setVisible(true);
            jLabel3.setVisible(true);
            jLabel9.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            txtNumeroMaterial.setVisible(false);
            txtVolumenMaterial.setVisible(false);

        } else if (cbTipoMaterial.getSelectedIndex() == 2) {

            txtAsignaturaMaterial.setEnabled(true);
            txtAñoMaterial.setEnabled(true);
            txtTituloMaterial.setEnabled(true);
            txtEditorialMaterial.setEnabled(true);
            txtNoCopiasMaterial.setEnabled(true);
            txtIsbnOIssnMaterial.setEnabled(true);
            txtAutores.setVisible(false);
            txtEdicionMaterial.setVisible(false);
            txtNoPaginas.setVisible(false);
            cbDiasPrestamo.setVisible(false);
            jLabel5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel9.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
            txtNumeroMaterial.setVisible(true);
            txtVolumenMaterial.setVisible(true);
            txtNumeroMaterial.setEnabled(true);
            txtVolumenMaterial.setEnabled(true);

        }


    }//GEN-LAST:event_cbTipoMaterialActionPerformed

    private void btnCancelarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMaterialActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        cbTipoMaterial.setEnabled(true);
        txtIsbnOIssnMaterial.setEditable(true);
        btnModificarMaterial.setEnabled(false);
        btnCancelarMaterial.setVisible(false);
        btnRegistrarMaterial.setEnabled(true);

    }//GEN-LAST:event_btnCancelarMaterialActionPerformed

    private void btnEliminarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMaterialActionPerformed
        // TODO add your handling code here:

        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Introduzca la isbn o issn del material bibliografico a eliminar"));

        if (controladorl.eliminarLibro(codigo)) {
            JOptionPane.showMessageDialog(null, "Eliminado Correctamente el libro",
                    "Informe", JOptionPane.INFORMATION_MESSAGE);
        } else if (controladorr.eliminarRevista(codigo)) {
            JOptionPane.showMessageDialog(null, "Eliminada Correctamente la revista",
                    "Informe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido eliminar");
        }

        listarTablas();
    }//GEN-LAST:event_btnEliminarMaterialActionPerformed

    private void btnBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMaterialActionPerformed
        // TODO add your handling code here:

        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la isbn o isnn del material bibliografico"));
        Libro libro = controladorl.buscarLibro(codigo);
        Revista revista = controladorr.buscarRevista(codigo);

        if (libro != null) {
            cbTipoMaterial.setSelectedIndex(1);
            cbTipoMaterial.setEnabled(false);
            txtAsignaturaMaterial.setText(libro.getAsignatura());
            txtIsbnOIssnMaterial.setText(String.valueOf(libro.getIsbnoIssn()));
            txtTituloMaterial.setText(libro.getTitulo());
            txtEditorialMaterial.setText(libro.getEditorial());
            txtAutores.setText(libro.getAutor());
            txtEdicionMaterial.setText(libro.getEdicion());
            txtAñoMaterial.setText(String.valueOf(libro.getAño()));
            txtNoCopiasMaterial.setText(String.valueOf(libro.getNumCopias()));
            txtNoPaginas.setText(String.valueOf(libro.getNumeroPaginas()));
            txtIsbnOIssnMaterial.setEditable(false);
            btnModificarMaterial.setEnabled(true);
            btnCancelarMaterial.setVisible(true);
            btnRegistrarMaterial.setEnabled(false);

            if (libro.getNumeroDiasPrestado() == (2)) {
                cbDiasPrestamo.setSelectedIndex(1);
            } else if (libro.getNumeroDiasPrestado() == (5)) {
                cbDiasPrestamo.setSelectedIndex(2);
            }

        } else if (revista != null) {
            cbTipoMaterial.setSelectedIndex(2);
            cbTipoMaterial.setEnabled(false);
            txtAsignaturaMaterial.setText(revista.getAsignatura());
            txtIsbnOIssnMaterial.setText(String.valueOf(revista.getIsbnoIssn()));
            txtTituloMaterial.setText(revista.getTitulo());
            txtEditorialMaterial.setText(revista.getEditorial());
            txtVolumenMaterial.setText(revista.getVolumen());
            txtAñoMaterial.setText(String.valueOf(revista.getAño()));
            txtNoCopiasMaterial.setText(String.valueOf(revista.getNumCopias()));
            txtNumeroMaterial.setText(String.valueOf(revista.getNumero()));
            txtIsbnOIssnMaterial.setEditable(false);
            btnModificarMaterial.setEnabled(true);
            btnCancelarMaterial.setVisible(true);
            btnRegistrarMaterial.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido encontrar el material");
        }


    }//GEN-LAST:event_btnBuscarMaterialActionPerformed

    private void txtAñoMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoMaterialKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9')) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoMaterialKeyTyped

    private void txtIsbnOIssnMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnOIssnMaterialKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIsbnOIssnMaterialKeyTyped

    private void txtNoPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPaginasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNoPaginasKeyTyped

    private void txtNoCopiasMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoCopiasMaterialKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNoCopiasMaterialKeyTyped

    private void txtNumeroMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroMaterialKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroMaterialKeyTyped

    private void btnModificarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMaterialActionPerformed
        // TODO add your handling code here:

        if (cbTipoMaterial.getSelectedIndex() == 1) {

            if (txtAsignaturaMaterial.getText().isEmpty()
                    || txtIsbnOIssnMaterial.getText().isEmpty()
                    || txtTituloMaterial.getText().isEmpty()
                    || txtAñoMaterial.getText().isEmpty()
                    || txtEditorialMaterial.getText().isEmpty()
                    || txtAutores.getText().isEmpty()
                    || txtNoCopiasMaterial.getText().isEmpty()
                    || txtNoPaginas.getText().isEmpty()
                    || cbDiasPrestamo.getSelectedIndex() == 0
                    || txtEdicionMaterial.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");

            } else {
                String asignaturaMaterial,
                        tituloMaterial,
                        editorialMaterial,
                        autoresLibro,
                        edicionlibro;

                int añoMaterial = 0, noCopiasMaterial = 0, noPaginasLibro = 0, isbnoissnMaterial = 0, diasPrestamoLibro = 0;

                asignaturaMaterial = txtAsignaturaMaterial.getText();
                isbnoissnMaterial = Integer.parseInt(txtIsbnOIssnMaterial.getText());
                tituloMaterial = txtTituloMaterial.getText();
                editorialMaterial = txtEditorialMaterial.getText();
                autoresLibro = txtAutores.getText();
                edicionlibro = txtEdicionMaterial.getText();
                añoMaterial = Integer.parseInt(txtAñoMaterial.getText());
                noCopiasMaterial = Integer.parseInt(txtNoCopiasMaterial.getText());
                noPaginasLibro = Integer.parseInt(txtNoPaginas.getText());

                switch (cbDiasPrestamo.getSelectedIndex()) {
                    case 1:
                        diasPrestamoLibro = 2;
                        break;
                    case 2:
                        diasPrestamoLibro = 5;
                        break;
                }

                controladorl.editarLibro(isbnoissnMaterial, autoresLibro, edicionlibro, noPaginasLibro, diasPrestamoLibro, tituloMaterial, editorialMaterial, añoMaterial, asignaturaMaterial, noCopiasMaterial);

                JOptionPane.showMessageDialog(null, "El libro se ha modificado ");
                limpiarCampos();
                listarTablas();
                cbTipoMaterial.setEnabled(true);
                txtIsbnOIssnMaterial.setEditable(true);
                btnModificarMaterial.setEnabled(false);
                btnCancelarMaterial.setVisible(false);
                btnRegistrarMaterial.setEnabled(true);
            }
        } else {

            if (txtAsignaturaMaterial.getText().isEmpty()
                    || txtIsbnOIssnMaterial.getText().isEmpty()
                    || txtTituloMaterial.getText().isEmpty()
                    || txtAñoMaterial.getText().isEmpty()
                    || txtEditorialMaterial.getText().isEmpty()
                    || txtVolumenMaterial.getText().isEmpty()
                    || txtNoCopiasMaterial.getText().isEmpty()
                    || txtNumeroMaterial.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");

            } else {

                String asignaturaMaterial,
                        tituloMaterial,
                        editorialMaterial,
                        volumen;

                int añoMaterial = 0, noCopiasMaterial = 0, numero = 0, isbnoissnMaterial = 0;

                asignaturaMaterial = txtAsignaturaMaterial.getText();
                isbnoissnMaterial = Integer.parseInt(txtIsbnOIssnMaterial.getText());
                tituloMaterial = txtTituloMaterial.getText();
                editorialMaterial = txtEditorialMaterial.getText();
                volumen = txtVolumenMaterial.getText();
                añoMaterial = Integer.parseInt(txtAñoMaterial.getText());
                noCopiasMaterial = Integer.parseInt(txtNoCopiasMaterial.getText());
                numero = Integer.parseInt(txtNumeroMaterial.getText());

                controladorr.editarRevista(isbnoissnMaterial, tituloMaterial, editorialMaterial, añoMaterial, asignaturaMaterial, noCopiasMaterial, volumen, numero);
                JOptionPane.showMessageDialog(null, "La revista se ha modificado ");
                limpiarCampos();
                listarTablas();
                cbTipoMaterial.setEnabled(true);
                txtIsbnOIssnMaterial.setEditable(true);
                btnModificarMaterial.setEnabled(false);
                btnCancelarMaterial.setVisible(false);
                btnRegistrarMaterial.setEnabled(true);
            }

        }

    }//GEN-LAST:event_btnModificarMaterialActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

        controladorl.guardarArchivoLb();
        controladorr.guardarArchivoRv();

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionMaterialBibliografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionMaterialBibliografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionMaterialBibliografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionMaterialBibliografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionMaterialBibliografico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMaterial;
    private javax.swing.JButton btnCancelarMaterial;
    private javax.swing.JButton btnEliminarMaterial;
    private javax.swing.JButton btnModificarMaterial;
    private javax.swing.JButton btnRegistrarMaterial;
    private javax.swing.JComboBox<String> cbDiasPrestamo;
    private javax.swing.JComboBox<String> cbTipoMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLibro;
    private javax.swing.JTable tblRevista;
    private javax.swing.JTextField txtAsignaturaMaterial;
    private javax.swing.JTextField txtAutores;
    private javax.swing.JTextField txtAñoMaterial;
    private javax.swing.JTextField txtEdicionMaterial;
    private javax.swing.JTextField txtEditorialMaterial;
    private javax.swing.JTextField txtIsbnOIssnMaterial;
    private javax.swing.JTextField txtNoCopiasMaterial;
    private javax.swing.JTextField txtNoPaginas;
    private javax.swing.JTextField txtNumeroMaterial;
    private javax.swing.JTextField txtTituloMaterial;
    private javax.swing.JTextField txtVolumenMaterial;
    // End of variables declaration//GEN-END:variables
}
